name: Deploy to Docker Hub
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t llm-api .
          docker tag llm-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/llm-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/llm-api:latest
